### ISSUE TITLE
Cute 404 page

### ISSUE THREAD

**Issue by mnm364** [noahpresler/semesterly#1016]
What happened to our crying emoji 404 page

![image](https://user-images.githubusercontent.com/8674966/29491317-013917c4-850d-11e7-90cc-063aabc072f8.png)

**Comment by noahpresler** [comment]
@maxyeo, @felixzhuologist do you know the issue here?

**Comment by maxyeo** [comment]
Was this deployed to prod? https://github.com/noahpresler/semesterly/pull/1002

**Comment by felixzhuologist** [comment]
This page is part of django rest framework's web browsable API (it just looks weird because the page style didn't load properly for some reason). I'm guessing what happened was: request is routed to CourseModalView -> `get_object_or_404` is called on EN.553.171 Fall 2017 course -> course is not found and Http404 is raised -> DRF's APIView overrides django's default Http404 handling and responds with html for the web browsable API. I'm not sure that FeatureFlowView needs to be an APIView so changing it to a normal django View should fix it, in the general case we would just need to write a custom exception handler which calls django's http404 handler for http404 exceptions
