### ISSUE TITLE
Setup on lubuntu

### ISSUE THREAD

**Issue by kristinyim** [noahpresler/semesterly#1025]
Multiple hackers at HopHacks Fall 2017 failed to set up their dev environment on Lubuntu when they ran `sudo npm install`

First error:
![img_6821](https://user-images.githubusercontent.com/14956724/30513255-54523068-9ace-11e7-9d1e-e3c45ffcd2fa.JPG)

Updated node and npm to the most recent versions. Error on `sudo npm install` is now:
![img_6820](https://user-images.githubusercontent.com/14956724/30513281-b15ce028-9ace-11e7-88e2-76d0a35ed3b9.JPG)
Attempted to fix permission through chown (option 1 on https://docs.npmjs.com/getting-started/fixing-npm-permissions). Still had same error so went through Lubuntu specific permission editing tactics but still not working.

The third approach was to download the specific repo that was causing the error manually. Was successful but when ran `sudo npm install` again, it still had the same error and I couldn't find where in the package.json it is listed as a download so couldn't remove it.

**Comment by rrkharse** [comment]
Most students running lubuntu are using Peter Froelich's version:
https://www.cs.jhu.edu/~phf/files/Lubuntu_16.04_LTS_i386_Reference.ova

This environment is based off of ubuntu 16.04 so I guess the docs also have to be updated to say "apt install" instead of "apt-get install" depending on ubuntu version.

I got everything installed except the chromedriver, because you can't install chrome on lubuntu (can't install chrome on 32 bit.) 

I can get semester.ly main webpage on localhost:8000 to load but not jhu.sem.ly:8000.
No errors.

I also installed the latest development version of nodejs to get things to work by:
wget -qO- https://deb.nodesource.com/setup_7.x | sudo bash -;
sudo apt install nodejs;

**Comment by mnm364** [comment]
Potential fix, see #1038 under the bullet point about NPM version 6. Close when confirmed

**Comment by Boccca2014** [comment]
I believe this was resolved
