### ISSUE TITLE
Adding Queen's University

### ISSUE THREAD

**Issue by astralcai** [noahpresler/semesterly#1140]
I remember two years ago Queen's University along with many other schools was still supported. Were they taken down? Is Queen's University in the process of being added now? If not, what's the process to add it?

**Comment by austinoboyle** [comment]
@kristinyim  May be able to speak more to this, but I believe Queen's legal went after them/requested their info be taken down because it was "private" (which I think is BS).  @astralcai Maybe if you go lobbied with Queen's for this you could get it back on here. I created a Solus scraper a while back that they were going to use to keep Queen's info up to date

**Comment by kristinyim** [comment]
Hi, yep we got a legal notice from Queen's University and removed Queens from the site and the codebase per their request. Since then, we've partnered with Johns Hopkins University and decreased the number of schools we support. Semester.ly is still open source so if you want to resolve the matter with Queen's and host a version of Semester.ly, you're more than welcome to!

**Comment by Boccca2014** [comment]
Closing, resolved above.
